name: Sync Repository

on:
  workflow_dispatch: # Permite que o workflow seja iniciado manualmente a partir da interface do GitHub

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove all files in the repository
      run: |
        rm -rf ./*
        rm -rf .[^.] .??*

    - name: Checkout Navez repository
      uses: actions/checkout@v3
      with:
        repository: strikeinthehouse/Navez
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Navez

    - name: Copy files from Navez repository
      run: |
        cp -r Navez/* .
        cp -r Navez/.* . 2>/dev/null || true
        rm -rf Navez

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m 'Sync with Navez repository'
        git push
