name: Baixando Lista

on:
  schedule:
    - cron: '*/15 * * * *'  # Agendado para rodar a cada 5 minutos
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v4

    - name: Configurar Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Deletar Log
      run: |
        rm -rf ./log.txt

    - name: Instalando dependências
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests streamlink beautifulsoup4 selenium yt_dlp

    - name: Verificar versão do Python
      run: |
        python3 --version

    - name: Verificar se YT.py está presente
      run: |
        if [ -f "scripts/YT.py" ]; then
          echo "YT.py encontrado"
        else
          echo "YT.py não encontrado. Verifique se o caminho está correto."
          exit 1
        fi

    - name: Rodar script pt.py
      run: |
        echo "Executando pt.py..."
        python3 pt.py

    - name: Rodar script vod.py
      run: |
        echo "Executando vod.py..."
        python3 vod.py

    - name: Rodar script it.py
      run: |
        echo "Executando it.py..."
        python3 it.py

    - name: Garantir alterações mais recentes do repositório remoto
      run: |
        git pull origin main || echo "Erro ao fazer pull, pode ser que já tenha as últimas alterações."

    - name: Adicionar Mudanças ao Controle de Versão
      run: |
        git add -A
        git status

    - name: Commit e Push
      run: |
        git diff --exit-code || git commit -m "Atualizar lista baixada"
        git push origin main || echo "Erro ao fazer push. Pode ser necessário revisar conflitos."
