name: Baixando Lista

on:
  schedule:
    - cron: '*/20 * * * *'  # Executa a cada 35 minutos
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Faz checkout do repositório
    - name: Checkout Repositório
      uses: actions/checkout@v4  # Versão atualizada para maior segurança e compatibilidade

    # Configura o ambiente virtual e instala dependências
    - name: Configurar Ambiente Virtual e Instalar Dependências
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip  # Atualiza o pip
        pip install streamlink selenium requests beautifulsoup4 lxml python-dateutil yt-dlp youtube-dl pytz

    # Instala ffmpeg para manipulação de mídia
    - name: Instalar ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # Executa os scripts Python
    - name: Executar Script vod.py
      run: |
        source venv/bin/activate
        python vod.py || { echo "Erro ao executar vod.py"; exit 1; }

    - name: Executar Script pt.py
      run: |
        source venv/bin/activate
        python pt.py || { echo "Erro ao executar pt.py"; exit 1; }

    - name: Executar Script it.py
      run: |
        source venv/bin/activate
        python it.py || { echo "Erro ao executar it.py"; exit 1; }

    # Adiciona mudanças ao controle de versão
    - name: Adicionar Mudanças
      run: |
        git add -A
        git status

    # Faz commit e push das mudanças
    - name: Commit e Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -m "Atualizar lista baixada" || echo "Nenhuma mudança para commitar."
        git push origin main
