name: Baixando Lista

on:
  schedule:
    - cron: '*/30 * * * *'  # Schedule to run every 30 minutos
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v4  # Updated to use a newer version

    - name: Configurar Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Deletar Log
      run: |
        rm -rf ./log.txt

    - name: Instalando dependências
      run: |
        # Install required Python dependencies
        python3 -m pip install --upgrade pip
        python3 -m pip install gdown requests streamlink beautifulsoup4 selenium yt_dlp youtube_dl

    - name: Verificar versão do Python
      run: |
        python3 --version

    - name: Verificar se pt.py está presente
      run: |
        if [ -f "pt.py" ]; then
          echo "pt.py encontrado"
        else
          echo "pt.py não encontrado. Verifique se o caminho está correto."
          exit 1
        fi

    - name: Rodar script pt.py
      run: |
        # Executa o script pt.py diretamente
        python3 pt.py

    - name: Verificar se vod.py está presente
      run: |
        if [ -f "vod.py" ]; then
          echo "vod.py encontrado"
        else
          echo "vod.py não encontrado. Verifique se o caminho está correto."
          exit 1
        fi

    - name: Rodar script vod.py
      run: |
        # Executa o script vod.py diretamente
        python3 vod.py

    - name: Verificar se it.py está presente
      run: |
        if [ -f "it.py" ]; then
          echo "it.py encontrado"
        else
          echo "it.py não encontrado. Verifique se o caminho está correto."
          exit 1
        fi

    - name: Rodar script it.py
      run: |
        # Executa o script it.py diretamente
        python3 it.py

    - name: Adicionar Mudanças ao Controle de Versão
      run: |
        git add -A
        git status

    - name: Garantir alterações mais recentes do repositório remoto
      run: |
        git pull origin main || echo "Erro ao fazer pull, pode ser que já tenha as últimas alterações."

    - name: Commit e Push
      run: |
        git commit -m "Atualizar lista baixada" || echo "Nenhuma mudança para commitar."
        git push origin main || echo "Erro ao fazer push. Pode ser necessário revisar conflitos."
