name: Baixando Lista

on:
  schedule:
    - cron: '*/15 * * * *'  # Executa a cada 15 minutos
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositório
      uses: actions/checkout@v4

    - name: Configurar Ambiente Virtual e Instalar Dependências
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install gdown streamlink selenium requests beautifulsoup4 lxml python-dateutil yt-dlp youtube-dl pytz haruhi-dl
        python3 -m pip install requests streamlink beautifulsoup4 selenium yt_dlp

    - name: Instalar ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # **Definição das variáveis de ambiente**
    - name: Definir Variáveis de Ambiente
      env:
        EMAIL_IA: ${{ secrets.EMAIL_IA }}
        SENHA_IA: ${{ secrets.SENHA_IA }}
      run: echo "Variáveis de ambiente carregadas com sucesso."

    - name: Executar Script vod.py
      run: |
        source venv/bin/activate
        python vod.py || { echo "Erro ao executar vod.py"; exit 1; }

    - name: Executar Script pt.py
      run: |
        source venv/bin/activate
        python pt.py || { echo "Erro ao executar pt.py"; exit 1; }

    - name: Executar Script it.py
      run: |
        source venv/bin/activate
        python it.py || { echo "Erro ao executar it.py"; exit 1; }

    - name: Adicionar Mudanças
      run: |
        git add -A
        git status

    - name: Garantir alterações mais recentes do repositório remoto
      run: |
        git pull origin main || echo "Erro ao fazer pull, pode ser que já tenha as últimas alterações."

    - name: Commit e Push
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -m "Atualizar lista baixada" || echo "Nenhuma mudança para commitar."
        git push origin main || echo "Erro ao fazer push. Pode ser necessário revisar conflitos."
