# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/1 * * *'

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Delete log
        run: |
          rm -rf ./log.txt

      - name: Instalando coisas
        run: |
          # Install required Python dependencies
          python3 -m pip install --upgrade pip
          python3 -m pip install requests streamlink beautifulsoup4 selenium yt_dlp
          
          
      - name: Main
        run: |
          pwd
          chmod +x TWITCH.sh
          ./TWITCH.sh

  
    # Step to run the Python script YT.py
      - name: Run YT.py script
        run: |
          # Ensure Python is installed
          python3 --version || sudo apt-get install python3
          
          # Navigate to the scripts folder and run the YT.py script
          cd scripts
          python3 YT.py

          
      # Adiciona mudanças ao controle de versão
      - name: Adicionar Mudanças
        run: |
          git add -A
          git status

    # Faz pull para garantir que temos as últimas mudanças do repositório remoto
      - name: Garantir alterações mais recentes do repositório remoto
        run: |
          git pull origin main || echo "Erro ao fazer pull, pode ser que já tenha as últimas alterações."

    # Faz commit e push das mudanças
      - name: Commit e Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -m "Atualizar lista baixada" || echo "Nenhuma mudança para commitar."
          git push origin main || echo "Erro ao fazer push. Pode ser necessário revisar conflitos."
